---
title: "Flex Dashboard Example"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
# library(flexdashboard)
# library(knitr)
# library(dplyr)
# library(kableExtra)
library(etn)
library(odbc)
```

```{r connecttoetn}

connect_to_etn2 <- function(username = Sys.getenv("userid"),
                           password = Sys.getenv("pwd")) {
  con <- DBI::dbConnect(
    odbc::odbc(),
    "ETN",
    uid = paste("", tolower(username), "", sep = ""),
    pwd = paste("", password, "", sep = "")
  )
  return(con)
}

con <- connect_to_etn2(Sys.getenv("userid"), Sys.getenv("pwd"))
# con <- etn::connect_to_etn(Sys.getenv("ETN_DB_USERID"), Sys.getenv("ETN_DB_PW"))
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

head(mtcars[, 1:4]) %>%
  knitr::kable(caption = "test caption") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
anim <- etn::get_animals(scientific_name = "Raja brachyura")

anim %>% head()
```

### Chart C

```{r}
summary(cars)
```