name: Connect to Remote PostgreSQL Database

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  connect-to-db:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y odbc-postgresql

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          R -e "install.packages(c('DBI', 'RPostgreSQL', 'remotes')"

      - name: Connect to Remote PostgreSQL Database
        run: |
          Rscript -e "
            library(DBI);
            library(RPostgreSQL);
            pgdrv <- DBI::dbDriver(drvName = 'PostgreSQL');
            con_OPdb <- dbConnect(pgdrv,
                                  dbname='open_protocol',
                                  host='pgetn.vliz.be', 
                                  port=5432,
                                  user=Sys.getenv('userid'),
                                  password=Sys.getenv('pwd'));
            print('Connection successful');
            dbDisconnect(con_OPdb);
          "
        env:
          userid: ${{ secrets.USERID }}  # Your GitHub Actions secret for the DB user ID
          pwd: ${{ secrets.PWD }}  # Your GitHub Actions secret for the DB password
